/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthVerifyPhoneRouteImport } from './routes/auth.verify-phone'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountTransactionsRouteImport } from './routes/account.transactions'
import { Route as AccountSupportRouteImport } from './routes/account.support'
import { Route as AccountRewardsRouteImport } from './routes/account.rewards'
import { Route as AccountReviewsRouteImport } from './routes/account.reviews'
import { Route as AccountRefundsRouteImport } from './routes/account.refunds'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountPayoutsRouteImport } from './routes/account.payouts'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountMarketingRouteImport } from './routes/account.marketing'
import { Route as AccountDeliveryRouteImport } from './routes/account.delivery'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountOrdersIndexRouteImport } from './routes/account.orders.index'
import { Route as AccountRefundsIdRouteImport } from './routes/account.refunds.$id'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyPhoneRoute = AuthVerifyPhoneRouteImport.update({
  id: '/verify-phone',
  path: '/verify-phone',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTransactionsRoute = AccountTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRewardsRoute = AccountRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRefundsRoute = AccountRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPayoutsRoute = AccountPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMarketingRoute = AccountMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDeliveryRoute = AccountDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountRefundsIdRoute = AccountRefundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountRefundsRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/delivery': typeof AccountDeliveryRoute
  '/account/marketing': typeof AccountMarketingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/payouts': typeof AccountPayoutsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/refunds': typeof AccountRefundsRouteWithChildren
  '/account/reviews': typeof AccountReviewsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/transactions': typeof AccountTransactionsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/refunds/$id': typeof AccountRefundsIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/delivery': typeof AccountDeliveryRoute
  '/account/marketing': typeof AccountMarketingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/payouts': typeof AccountPayoutsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/refunds': typeof AccountRefundsRouteWithChildren
  '/account/reviews': typeof AccountReviewsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/transactions': typeof AccountTransactionsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account': typeof AccountIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/refunds/$id': typeof AccountRefundsIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/payments': typeof PaymentsRoute
  '/profile': typeof ProfileRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/delivery': typeof AccountDeliveryRoute
  '/account/marketing': typeof AccountMarketingRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/payouts': typeof AccountPayoutsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/refunds': typeof AccountRefundsRouteWithChildren
  '/account/reviews': typeof AccountReviewsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/support': typeof AccountSupportRoute
  '/account/transactions': typeof AccountTransactionsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-phone': typeof AuthVerifyPhoneRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$category': typeof ShopCategoryRoute
  '/account/': typeof AccountIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/refunds/$id': typeof AccountRefundsIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/delivery'
    | '/account/marketing'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payouts'
    | '/account/profile'
    | '/account/refunds'
    | '/account/reviews'
    | '/account/rewards'
    | '/account/support'
    | '/account/transactions'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/product/$id'
    | '/shop/$category'
    | '/account/'
    | '/account/orders/$id'
    | '/account/refunds/$id'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/delivery'
    | '/account/marketing'
    | '/account/notifications'
    | '/account/payouts'
    | '/account/profile'
    | '/account/refunds'
    | '/account/reviews'
    | '/account/rewards'
    | '/account/support'
    | '/account/transactions'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/product/$id'
    | '/shop/$category'
    | '/account'
    | '/account/orders/$id'
    | '/account/refunds/$id'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/payments'
    | '/profile'
    | '/seller'
    | '/shop'
    | '/wishlist'
    | '/account/addresses'
    | '/account/delivery'
    | '/account/marketing'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payouts'
    | '/account/profile'
    | '/account/refunds'
    | '/account/reviews'
    | '/account/rewards'
    | '/account/support'
    | '/account/transactions'
    | '/account/wishlist'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/sellers'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/verify-email'
    | '/auth/verify-phone'
    | '/product/$id'
    | '/shop/$category'
    | '/account/'
    | '/account/orders/$id'
    | '/account/refunds/$id'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  PaymentsRoute: typeof PaymentsRoute
  ProfileRoute: typeof ProfileRoute
  SellerRoute: typeof SellerRoute
  ShopRoute: typeof ShopRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-phone': {
      id: '/auth/verify-phone'
      path: '/verify-phone'
      fullPath: '/auth/verify-phone'
      preLoaderRoute: typeof AuthVerifyPhoneRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/transactions': {
      id: '/account/transactions'
      path: '/transactions'
      fullPath: '/account/transactions'
      preLoaderRoute: typeof AccountTransactionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/support': {
      id: '/account/support'
      path: '/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/rewards': {
      id: '/account/rewards'
      path: '/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AccountRewardsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/refunds': {
      id: '/account/refunds'
      path: '/refunds'
      fullPath: '/account/refunds'
      preLoaderRoute: typeof AccountRefundsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payouts': {
      id: '/account/payouts'
      path: '/payouts'
      fullPath: '/account/payouts'
      preLoaderRoute: typeof AccountPayoutsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/marketing': {
      id: '/account/marketing'
      path: '/marketing'
      fullPath: '/account/marketing'
      preLoaderRoute: typeof AccountMarketingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/delivery': {
      id: '/account/delivery'
      path: '/delivery'
      fullPath: '/account/delivery'
      preLoaderRoute: typeof AccountDeliveryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/refunds/$id': {
      id: '/account/refunds/$id'
      path: '/$id'
      fullPath: '/account/refunds/$id'
      preLoaderRoute: typeof AccountRefundsIdRouteImport
      parentRoute: typeof AccountRefundsRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
  }
}

interface AccountOrdersRouteChildren {
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRefundsRouteChildren {
  AccountRefundsIdRoute: typeof AccountRefundsIdRoute
}

const AccountRefundsRouteChildren: AccountRefundsRouteChildren = {
  AccountRefundsIdRoute: AccountRefundsIdRoute,
}

const AccountRefundsRouteWithChildren = AccountRefundsRoute._addFileChildren(
  AccountRefundsRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountDeliveryRoute: typeof AccountDeliveryRoute
  AccountMarketingRoute: typeof AccountMarketingRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountPayoutsRoute: typeof AccountPayoutsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountRefundsRoute: typeof AccountRefundsRouteWithChildren
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountRewardsRoute: typeof AccountRewardsRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AccountTransactionsRoute: typeof AccountTransactionsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountDeliveryRoute: AccountDeliveryRoute,
  AccountMarketingRoute: AccountMarketingRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountPayoutsRoute: AccountPayoutsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountRefundsRoute: AccountRefundsRouteWithChildren,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountRewardsRoute: AccountRewardsRoute,
  AccountSupportRoute: AccountSupportRoute,
  AccountTransactionsRoute: AccountTransactionsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSellersRoute: typeof AdminSellersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSellersRoute: AdminSellersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyPhoneRoute: typeof AuthVerifyPhoneRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyPhoneRoute: AuthVerifyPhoneRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ShopRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCategoryRoute: ShopCategoryRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  PaymentsRoute: PaymentsRoute,
  ProfileRoute: ProfileRoute,
  SellerRoute: SellerRoute,
  ShopRoute: ShopRouteWithChildren,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
